@startuml
left to right direction
skinparam packageStyle rectangle

actor "Juez Administrador" as juez
actor "Persona" as persona

rectangle "Sistema Administrador de Procesos Judiciales" {
    usecase "C.U.1 Registrar Proceso" as CU1
    usecase "C.U.1.1 Ingresar Datos del Proceso" as CU11
    usecase "C.U.1.2 Seleccionar Tipo de Proceso" as CU12
    usecase "C.U.1.3 Seleccionar Tipo de Entrada" as CU13
}

juez --> CU1

CU1 .> CU11 : <<include>>
CU1 .> CU12 : <<include>>
CU1 .> CU13 : <<include>>

persona --> CU11
persona --> CU12
persona --> CU13

note right of CU11
tipo de proceso,
número,
demandante,
demandado,
tipo de entrada,
fecha de entrada
end note

@enduml
