@startuml
left to right direction
skinparam packageStyle rectangle

actor "Juez Administrador" as juez

rectangle "Caso de Uso 5: Buscar Persona" {
    usecase "C.U.5.1 Buscar Persona" as CU51
    usecase "C.U.5.1.1 Ingresar cédula de persona a buscar" as CU511
}

juez --> CU51
CU51 .> CU511 : <<include>>

@enduml
