@startuml
left to right direction
skinparam packageStyle rectangle

actor "Juez administrador" as juez

rectangle "Caso de Uso 3: Buscar Proceso" {
    usecase "C.U.3 Buscar proceso" as CU31
    usecase "C.U.3.1 Ingresar número de proceso" as CU311
}

juez --> CU31
CU31 .> CU311 : <<include>>

@enduml
