@startuml
left to right direction
skinparam packageStyle rectangle

actor "Juez administrador" as juez

rectangle "Caso de Uso 2: Agregar Actuación" {
    usecase "C.U.2 Agregar actuación" as CU21
    usecase "C.U.2.1 Ingresar número de proceso" as CU211
    usecase "C.U.2.2 Seleccionar tipo de actuación" as CU212
    usecase "C.U.2.3 Ingresar fecha de ingreso" as CU213
    usecase "C.U.2.4 Seleccionar descripción" as CU214
}

juez --> CU21

CU21 .> CU211 : <<include>>
CU21 .> CU212 : <<include>>
CU21 .> CU213 : <<include>>
CU21 .> CU214 : <<include>>

@enduml
