@startuml
left to right direction
skinparam packageStyle rectangle

actor "Juez Administrador" as juez

rectangle "Caso de Uso 7: Añadir descripciones de actuaciones" {
    usecase "C.U.7 Añadir descripciones de actuaciones" as CU7
    usecase "C.U.7.1 Seleccionar el tipo de proceso" as CU71
    usecase "C.U.7.2 Seleccionar el tipo de actuación" as CU72
    usecase "C.U.7.3 Añadir la descripción" as CU73
}

juez --> CU7
CU7 .> CU71 : <<include>>
CU7 .> CU72 : <<include>>
CU7 .> CU73 : <<include>>


@enduml
